### ISSUE TITLE
Ошибка запроса к api при обновлении содержимого во вкладке Derivative

### ISSUE THREAD

**Issue by ValesValesskiy** [AndreiBelokopytov/magnetar#2]
Периодические запросы к апи https://testnet.api.injective.dev/chronos/v1/derivative/market_summary_all?resolution=24h падают с ошибкой 404. Если привести строку к виду  https://testnet.api.injective.dev/api/chronos/v1/derivative/market_summary_all?resolution=24h, запрос выполняется со статусом 200.
![image](https://user-images.githubusercontent.com/79196988/143689704-ba15ae4b-602c-4221-ac3a-5242159d76d3.png)

**Comment by AndreiBelokopytov** [comment]
Fixed in  [cc14bff282213465176691563c16b867c66e90b7](https://github.com/AndreiBelokopytov/magnetar/commit/cc14bff282213465176691563c16b867c66e90b7)
